const keyboard_layout = [
    {name: 'A1', white: true, offset: 0},
    {name: 'A#1', white: false, offset: 1},
    {name: 'B1', white: true, offset: 1},
    {name: 'C1', white: true, offset: 2},
    {name: 'C#1', white: false, offset: 3},
    {name: 'D1', white: true, offset: 3},
    {name: 'D#1', white: false, offset: 4},
    {name: 'E1', white: true, offset: 4},
    {name: 'F1', white: true, offset: 5},
    {name: 'F#1', white: false, offset: 6},
    {name: 'G1', white: true, offset: 6},
    {name: 'G#1', white: false, offset: 7},

    {name: 'A2', white: true, offset: 7},
    {name: 'A#2', white: false, offset: 8},
    {name: 'B2', white: true, offset: 8},
    {name: 'C2', white: true, offset: 9},
    {name: 'C#2', white: false, offset: 10},
    {name: 'D2', white: true, offset: 10},
    {name: 'D#2', white: false, offset: 11},
    {name: 'E2', white: true, offset: 11},
    {name: 'F2', white: true, offset: 12},
    {name: 'F#2', white: false, offset: 13},
    {name: 'G2', white: true, offset: 13},
    {name: 'G#2', white: false, offset: 14},

    {name: 'A3', white: true, offset: 14},
    {name: 'A#3', white: false, offset: 15},
    {name: 'B3', white: true, offset: 15},
    {name: 'C3', white: true, offset: 16},
    {name: 'C#3', white: false, offset: 17},
    {name: 'D3', white: true, offset: 17},
    {name: 'D#3', white: false, offset: 18},
    {name: 'E3', white: true, offset: 18},
    {name: 'F3', white: true, offset: 19},
    {name: 'F#3', white: false, offset: 20},
    {name: 'G3', white: true, offset: 20},
    {name: 'G#3', white: false, offset: 21},

    {name: 'A4', white: true, offset: 21},
    {name: 'A#4', white: false, offset: 22},
    {name: 'B4', white: true, offset: 22},
    {name: 'C4', white: true, offset: 23},
    {name: 'C#4', white: false, offset: 24},
    {name: 'D4', white: true, offset: 24},
    {name: 'D#4', white: false, offset: 25},
    {name: 'E4', white: true, offset: 25},
    {name: 'F4', white: true, offset: 26},
    {name: 'F#4', white: false, offset: 27},
    {name: 'G4', white: true, offset: 27},
    {name: 'G#4', white: false, offset: 28},

    {name: 'A5', white: true, offset: 28},
    {name: 'A#5', white: false, offset: 29},
    {name: 'B5', white: true, offset: 29},
    {name: 'C5', white: true, offset: 30},
    {name: 'C#5', white: false, offset: 31},
    {name: 'D5', white: true, offset: 31},
    {name: 'D#5', white: false, offset: 32},
    {name: 'E5', white: true, offset: 32},
    {name: 'F5', white: true, offset: 33},
    {name: 'F#5', white: false, offset: 34},
    {name: 'G5', white: true, offset: 34},
    {name: 'G#5', white: false, offset: 35},

    {name: 'A6', white: true, offset: 35},
    {name: 'A#6', white: false, offset: 36},
    {name: 'B6', white: true, offset: 36},
    {name: 'C6', white: true, offset: 37},
    {name: 'C#6', white: false, offset: 38},
    {name: 'D6', white: true, offset: 38},
    {name: 'D#6', white: false, offset: 39},
    {name: 'E6', white: true, offset: 39},
    {name: 'F6', white: true, offset: 40},
    {name: 'F#6', white: false, offset: 41},
    {name: 'G6', white: true, offset: 41},
    {name: 'G#6', white: false, offset: 42},

    {name: 'A7', white: true, offset: 42},
    {name: 'A#7', white: false, offset: 43},
    {name: 'B7', white: true, offset: 43},
    {name: 'C7', white: true, offset: 44},
    {name: 'C#7', white: false, offset: 45},
    {name: 'D7', white: true, offset: 45},
    {name: 'D#7', white: false, offset: 46},
    {name: 'E7', white: true, offset: 46},
    {name: 'F7', white: true, offset: 47},
    {name: 'F#7', white: false, offset: 48},
    {name: 'G7', white: true, offset: 48},
    {name: 'G#7', white: false, offset: 49},

    {name: 'A8', white: true, offset: 49},
    {name: 'A#8', white: false, offset: 50},
    {name: 'B8', white: true, offset: 50},
];

keyboard_layout.forEach((e,i) => e.index = i);